[workspace]

resolver = "2"

members = [
    "crates/ibc",
]

exclude = [
    "ci/no-std-check",
]

[patch.crates-io]
ibc-proto  = { git = "https://github.com/octopus-network/ibc-proto-rs.git",  branch = "add-codec-borsh-for-any" }