[package]
name         = "ibc-client-tendermint-cw"
authors      = { workspace = true }
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
rust-version = { workspace = true }
version      = { workspace = true }
keywords     = [ "ibc", "light-client", "CosmWasm", "ICS-07", "Tendermint" ]
readme       = "./../README.md"

description = """
    Contains the implementation of the ICS-07 Tendermint Client logic as a CosmWasm contract.
    It leverages the `ibc-client-cw` crate to integrate the Tendermint light client into a CosmWasm contract.
"""

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
# ibc dependencies
ibc-core              = { workspace = true }
ibc-client-cw         = { workspace = true }
ibc-client-tendermint = { workspace = true }

# cosmwasm dependencies
cosmwasm-std = { workspace = true }

[dev-dependencies]
ibc-testkit        = { workspace = true }
serde-json         = { workspace = true }
tendermint         = { workspace = true }
tendermint-testgen = { workspace = true }

[features]
default = [ "std" ]
std = [
  "ibc-core/std",
  "ibc-client-cw/std",
  "ibc-client-tendermint/std",
]
